export default [
   {
      symbol: "AAPL",
      last_close: 150.25,
      mandelbrot_channel_buy: 148.5,
      mandelbrot_channel_sell: 152.0,
      up_down: "Up",
      risk_reward: 1.5,
      asset_class: "Equity",
      sector: "Technology",
      humbl_suggestion: "Hold",
   },
   {
      symbol: "GOOGL",
      last_close: 2750.8,
      mandelbrot_channel_buy: 2725.0,
      mandelbrot_channel_sell: 2775.0,
      up_down: "Down",
      risk_reward: 1.2,
      asset_class: "Equity",
      sector: "Technology",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "XOM",
      last_close: 62.75,
      mandelbrot_channel_buy: 61.5,
      mandelbrot_channel_sell: 64.0,
      up_down: "Up",
      risk_reward: 0.8,
      asset_class: "Equity",
      sector: "Energy",
      humbl_suggestion: "Sell",
   },
   {
      symbol: "JPM",
      last_close: 155.3,
      mandelbrot_channel_buy: 153.0,
      mandelbrot_channel_sell: 157.5,
      up_down: "Up",
      risk_reward: 1.3,
      asset_class: "Equity",
      sector: "Financials",
      humbl_suggestion: "Hold",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
   {
      symbol: "PG",
      last_close: 140.5,
      mandelbrot_channel_buy: 139.0,
      mandelbrot_channel_sell: 142.0,
      up_down: "Down",
      risk_reward: 0.9,
      asset_class: "Equity",
      sector: "Consumer Staples",
      humbl_suggestion: "Buy",
   },
];
